package org.gbif.cordra.backfill;

import static org.elasticsearch.hadoop.cfg.ConfigurationOptions.ES_NODES;
import static org.elasticsearch.hadoop.cfg.ConfigurationOptions.ES_SERIALIZATION_WRITER_BYTES_CLASS;

import com.fasterxml.jackson.databind.JsonNode;
import com.github.fge.jsonschema.main.JsonSchema;
import com.github.fge.jsonschema.main.JsonSchemaFactory;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.cnri.cordra.CordraObjectSchemaValidator;
import net.cnri.cordra.CordraService;
import net.cnri.cordra.JsonSchemaFactoryFactory;
import net.cnri.cordra.api.CordraObject;
import net.cnri.cordra.indexer.elasticsearch.DocumentBuilderElasticsearch;
import net.cnri.cordra.schema.LazySchema;
import net.cnri.cordra.schema.SchemaNodeAndUri;
import net.cnri.cordra.schema.fge.FgeJsonSchemaUtil;
import net.cnri.cordra.util.JacksonUtil;
import org.elasticsearch.hadoop.cfg.ConfigurationOptions;
import org.elasticsearch.hadoop.cfg.PropertiesSettings;
import org.elasticsearch.hadoop.mr.WritableBytesConverter;
import org.elasticsearch.hadoop.rest.Resource;
import org.elasticsearch.hadoop.rest.RestClient;
import org.elasticsearch.hadoop.rest.bulk.BulkProcessor;
import org.elasticsearch.hadoop.serialization.builder.NoOpValueWriter;
import org.elasticsearch.hadoop.serialization.bulk.BulkCommands;
import org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter;
import org.elasticsearch.hadoop.util.BytesArray;
import org.elasticsearch.hadoop.util.BytesRef;
import org.elasticsearch.hadoop.util.EsMajorVersion;
import org.gbif.cordra.storage.hbase.HBaseStorage;

public class Test {

  private static final String SCHEMA =
      "{\n"
          + "  \"type\": \"object\",\n"
          + "  \"required\": [\n"
          + "    \"scientificName\"\n"
          + "  ],\n"
          + "  \"properties\": {\n"
          + "    \"id\": {\n"
          + "      \"type\": \"string\",\n"
          + "      \"cordra\": {\n"
          + "        \"type\": {\n"
          + "          \"autoGeneratedField\": \"handle\"\n"
          + "        }\n"
          + "      }\n"
          + "    },\n"
          + "    \"scientificName\": {\n"
          + "      \"type\": \"string\",\n"
          + "      \"maxLength\": 128,\n"
          + "      \"title\": \"ScientificName\",\n"
          + "      \"cordra\": {\n"
          + "        \"preview\": {\n"
          + "          \"showInPreview\": true,\n"
          + "          \"isPrimary\": true\n"
          + "        }\n"
          + "      }\n"
          + "    }\n"
          + "  }\n"
          + "}";

  static String exampleAsJSON =
      "{\"species\" : \"Volvulella acuminata\", \"classKey\" : 225, \"familyKey\" : 6520446, \"catalogNumber\" : \"ZMBN 105730\", \"acceptedTaxonKey\" : 4359505, \"publishingorgkey\" : \"3f3967bf-ecc7-4455-ba89-4e0ab6d6fd3c\", \"collectionCode\" : \"Boblesnegler\", \"occurrenceID\" : \"urn:catalog:BG:Boblesnegler:ZMBN 105730\", \"datasetName\" : \"Cephalaspidean Gastropods\", \"year\" : 2014, \"taxonKey\" : 4359505, \"phylum\" : \"Mollusca\", \"taxonRank\" : \"SPECIES\", \"kingdom\" : \"Animalia\", \"scientificName\" : \"Volvulella acuminata (Bruguière, 1792)\", \"genericName\" : \"Volvulella\", \"datasetKey\" : \"8f3081d6-42e6-44df-972a-a5c0c991f3ca\", \"speciesKey\" : 4359505, \"genus\" : \"Volvulella\", \"phylumKey\" : 52, \"order\" : \"Cephalaspidea\", \"eventDate\" : \"2014-06-10 00:00:00\", \"countryCode\" : \"NO\", \"publisher\" : \"University of Bergen: University Museum\", \"acceptedScientificName\" : \"Volvulella acuminata (Bruguière, 1792)\", \"recordedBy\" : \"HM2014\\/06\", \"orderKey\" : 454, \"institutionCode\" : \"BG\", \"recordedByID\" : WrappedArray(), \"family\" : \"Rhizoridae\", \"specificEpithet\" : \"acuminata\", \"day\" : 10, \"gbifId\" : 1253519522, \"decimalLongitude\" : 5.44881, \"kingdomKey\" : 1, \"preparations\" : \"EtOH\", \"decimalLatitude\" : 59.02985, \"genusKey\" : 2291681, \"month\" : 6, \"basisOfRecord\" : \"PRESERVED_SPECIMEN\"}";

  public static void main(String[] args) throws Exception {
    CordraObject co = new CordraObject();
    co.id = "20.5000.123.TEST/2916087871";
    co.type = "Occurrence";
    // co.content = JsonParser.parseString(exampleAsJSON);
    co.content =
        JsonParser.parseString("    {\"scientificName\":\"Abies alba\", \"id\":\"" + co.id + "\"}");

    co.metadata = new CordraObject.Metadata();
    co.metadata.createdBy = "admin";
    co.metadata.createdOn = 1643375628829l;
    co.metadata.txnId = 1643375628829011l;
    co.metadata.modifiedBy = "admin";
    co.metadata.modifiedOn = 1643375628829l;
    co.metadata.internalMetadata = new JsonObject();

    HBaseStorage storage =
        new HBaseStorage(
            "cordra", "3", "c4zk1.gbif-uat.org,c4zk2.gbif-uat.org,c4zk3.gbif-uat.org:2181");
    storage.create(co);

    Map<String, JsonNode> pointerToSchema = new HashMap<>();
    DocumentBuilderElasticsearch builder = new DocumentBuilderElasticsearch(false, null);
    Map<String, List<Object>> doc = builder.build(co, false, pointerToSchema, Lists.newArrayList());

    Gson gson = new Gson();
    String result = gson.toJson(doc);
    System.err.println(result);

    PropertiesSettings settings = new PropertiesSettings();
    settings.setProperty(ES_NODES, "uc6n10.gbif.org");
    settings.setResourceWrite("cordra");
    settings.setInternalVersion(EsMajorVersion.V_7_X);
    settings.setProperty(
        ConfigurationOptions.ES_SERIALIZATION_WRITER_VALUE_CLASS, NoOpValueWriter.class.getName());
    settings.setProperty(
        ES_SERIALIZATION_WRITER_BYTES_CLASS, WritableBytesConverter.class.getName());
    settings.setProperty(ConfigurationOptions.ES_INPUT_JSON, "true");

    Resource writeResource = new Resource(settings, false);

    RestClient client = new RestClient(settings);

    BytesArray document =
        //            new BytesArray(
        //                    "{\"index\":{\"_id\":\"20.5000.123.TEST/CODE\"}}\n"
        //                    + result
        //            );
        new BytesArray(
            "" // ""{\"index\":{\"_id\":\"20.5000.123.TEST/574936220\"}}\n"
                + result);
    // + "{\"aclRead\":[\"missing\"],\"sort_/acceptedScientificName\":[\"Vicia lenticula (Hoppe)
    // Janka\"],\"sort_dtindexed\":[\"20220126155304537\"],\"type\":[\"Occurrence\"],\"sort_/occurrenceID\":[\"http://data.rbge.org.uk/herb/E00370188\"],\"sort_id\":[\"574936220\"],\"/genus\":[\"Vicia\"],\"/preparations\":[\"herbarium specimen of unspecified type\"],\"sort_/ext_multimedia\":[\"[ {\\n  \\\"type\\\" : null,\\n  \\\"format\\\" : null,\\n  \\\"identifier\\\" : \\\"https://iiif.rbge.org.uk/herb/iiif/E00370188/manifest\\\",\\n  \\\"references\\\" : null,\\n  \\\"title\\\" : null,\\n  \\\"description\\\" : \\\"IIIF Manifest for specimen E00370188\\\",\\n  \\\"source\\\" : null,\\n  \\\"audience\\\" : null,\\n  \\\"created\\\" : null,\\n  \\\"creator\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"contributor\\\" : null,\\n  \\\"publisher\\\" : null,\\n  \\\"license\\\" : \\\"http://creativecommons.org/publicdomain/zero/1.0/\\\",\\n  \\\"rightsHolder\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"datasetId\\\" : null\\n}, {\\n  \\\"type\\\" : \\\"StillImage\\\",\\n  \\\"format\\\" : \\\"image/jpeg\\\",\\n  \\\"identifier\\\" : \\\"http://repo.rbge.org.uk/image_server.php?kind\\u003d1500\\u0026path_base64\\u003dL2hlcmJhcml1bV9zcGVjaW1lbl9zY2Fucy9FMDAvMzcwLzE4OC8xNzk2OTQuanBn\\\",\\n  \\\"references\\\" : null,\\n  \\\"title\\\" : null,\\n  \\\"description\\\" : \\\"Image of herbarium specimen E00370188 by Specimen Digitisation Pipeline\\\",\\n  \\\"source\\\" : null,\\n  \\\"audience\\\" : null,\\n  \\\"created\\\" : null,\\n  \\\"creator\\\" : \\\"Specimen Digitisation Pipeline\\\",\\n  \\\"contributor\\\" : null,\\n  \\\"publisher\\\" : null,\\n  \\\"license\\\" : \\\"http://c\"],\"sort_/gbifId\":[\"574936220\"],\"id\":[\"574936220\"],\"sort_/scientificName\":[\"Lens ervoides (Brign.) Grande\"],\"sort_/acceptedTaxonKey\":[\"2946873\"],\"/classKey\":[\"220\"],\"indexVersion\":[\"net.cnri.cordra.indexer.elasticsearch.DocumentBuilderElasticsearch 1\"],\"sort_/specificEpithet\":[\"ervoides\"],\"/acceptedScientificName\":[\"Vicia lenticula (Hoppe) Janka\"],\"objmodified\":[\"19700101000000000\"],\"/acceptedTaxonKey\":[\"2946873\"],\"sort_objmodified\":[\"19700101000000000\"],\"/basisOfRecord\":[\"PRESERVED_SPECIMEN\"],\"/orderKey\":[\"1370\"],\"/recordedBy\":[\"Siehe, Walter\"],\"sort_objatt_internal.modified\":[\"0\"],\"sort_/otherCatalogNumbers\":[\"BGBASE:382124\"],\"sort_/catalogNumber\":[\"E00370188\"],\"sort_objatt_internal.created\":[\"0\"],\"sort_/order\":[\"Fabales\"],\"/speciesKey\":[\"2946873\"],\"valid\":[\"true\"],\"/collectionCode\":[\"E\"],\"sort_objcreated\":[\"19700101000000000\"],\"/genericName\":[\"Lens\"],\"sort_/taxonKey\":[\"5350011\"],\"/scientificName\":[\"Lens ervoides (Brign.) Grande\"],\"sort_/datasetName\":[\"Royal Botanic Garden Edinburgh Herbarium (E)\"],\"/institutionCode\":[\"E\"],\"/publishingorgkey\":[\"98e934b0-5f31-11de-b67e-b8a03c50a862\"],\"/publisher\":[\"Royal Botanic Garden Edinburgh\"],\"sort_/orderKey\":[\"1370\"],\"sort_type\":[\"Occurrence\"],\"sort_/genus\":[\"Vicia\"],\"metadata/modifiedOn\":[\"0\"],\"sort_/phylumKey\":[\"7707728\"],\"/familyKey\":[\"5386\"],\"sort_metadata/modifiedOn\":[\"0\"],\"sort_/recordNumber\":[\"85\"],\"objcreated\":[\"19700101000000000\"],\"/specificEpithet\":[\"ervoides\"],\"/phylum\":[\"Tracheophyta\"],\"/countryCode\":[\"TR\"],\"/phylumKey\":[\"7707728\"],\"sort_/institutionCode\":[\"E\"],\"/species\":[\"Vicia lenticula\"],\"/taxonKey\":[\"5350011\"],\"sort_/datasetKey\":[\"bf2a4bf0-5f31-11de-b67e-b8a03c50a862\"],\"/family\":[\"Fabaceae\"],\"/kingdomKey\":[\"6\"],\"sort_/genusKey\":[\"2974751\"],\"sort_/collectionCode\":[\"E\"],\"/recordedByID\":[\"WrappedArray()\"],\"/genusKey\":[\"2974751\"],\"/otherCatalogNumbers\":[\"BGBASE:382124\"],\"/taxonRank\":[\"SPECIES\"],\"sort_/phylum\":[\"Tracheophyta\"],\"sort_/speciesKey\":[\"2946873\"],\"sort_/family\":[\"Fabaceae\"],\"sort_/species\":[\"Vicia lenticula\"],\"objatt_type\":[\"Occurrence\"],\"sort_metadata/createdOn\":[\"0\"],\"sort_/familyKey\":[\"5386\"],\"sort_/kingdomKey\":[\"6\"],\"sort_objatt_type\":[\"Occurrence\"],\"/kingdom\":[\"Plantae\"],\"sort_/taxonRank\":[\"SPECIES\"],\"/recordNumber\":[\"85\"],\"/occurrenceID\":[\"http://data.rbge.org.uk/herb/E00370188\"],\"aclWrite\":[\"missing\"],\"sort_/classKey\":[\"220\"],\"/ext_multimedia\":[\"[ {\\n  \\\"type\\\" : null,\\n  \\\"format\\\" : null,\\n  \\\"identifier\\\" : \\\"https://iiif.rbge.org.uk/herb/iiif/E00370188/manifest\\\",\\n  \\\"references\\\" : null,\\n  \\\"title\\\" : null,\\n  \\\"description\\\" : \\\"IIIF Manifest for specimen E00370188\\\",\\n  \\\"source\\\" : null,\\n  \\\"audience\\\" : null,\\n  \\\"created\\\" : null,\\n  \\\"creator\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"contributor\\\" : null,\\n  \\\"publisher\\\" : null,\\n  \\\"license\\\" : \\\"http://creativecommons.org/publicdomain/zero/1.0/\\\",\\n  \\\"rightsHolder\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"datasetId\\\" : null\\n}, {\\n  \\\"type\\\" : \\\"StillImage\\\",\\n  \\\"format\\\" : \\\"image/jpeg\\\",\\n  \\\"identifier\\\" : \\\"http://repo.rbge.org.uk/image_server.php?kind\\u003d1500\\u0026path_base64\\u003dL2hlcmJhcml1bV9zcGVjaW1lbl9zY2Fucy9FMDAvMzcwLzE4OC8xNzk2OTQuanBn\\\",\\n  \\\"references\\\" : null,\\n  \\\"title\\\" : null,\\n  \\\"description\\\" : \\\"Image of herbarium specimen E00370188 by Specimen Digitisation Pipeline\\\",\\n  \\\"source\\\" : null,\\n  \\\"audience\\\" : null,\\n  \\\"created\\\" : null,\\n  \\\"creator\\\" : \\\"Specimen Digitisation Pipeline\\\",\\n  \\\"contributor\\\" : null,\\n  \\\"publisher\\\" : null,\\n  \\\"license\\\" : \\\"http://creativecommons.org/publicdomain/zero/1.0/\\\",\\n  \\\"rightsHolder\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"datasetId\\\" : null\\n} ]\"],\"sort_/preparations\":[\"herbarium specimen of unspecified type\"],\"/datasetKey\":[\"bf2a4bf0-5f31-11de-b67e-b8a03c50a862\"],\"sort_/recordedByID\":[\"WrappedArray()\"],\"internal.all\":[\"Vicia lenticula\",\"220\",\"5386\",\"BGBASE:382124\",\"E00370188\",\"2946873\",\"98e934b0-5f31-11de-b67e-b8a03c50a862\",\"E\",\"http://data.rbge.org.uk/herb/E00370188\",\"Royal Botanic Garden Edinburgh Herbarium (E)\",\"5350011\",\"Tracheophyta\",\"SPECIES\",\"Plantae\",\"Lens ervoides (Brign.) Grande\",\"[ {\\n  \\\"type\\\" : null,\\n  \\\"format\\\" : null,\\n  \\\"identifier\\\" : \\\"https://iiif.rbge.org.uk/herb/iiif/E00370188/manifest\\\",\\n  \\\"references\\\" : null,\\n  \\\"title\\\" : null,\\n  \\\"description\\\" : \\\"IIIF Manifest for specimen E00370188\\\",\\n  \\\"source\\\" : null,\\n  \\\"audience\\\" : null,\\n  \\\"created\\\" : null,\\n  \\\"creator\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"contributor\\\" : null,\\n  \\\"publisher\\\" : null,\\n  \\\"license\\\" : \\\"http://creativecommons.org/publicdomain/zero/1.0/\\\",\\n  \\\"rightsHolder\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"datasetId\\\" : null\\n}, {\\n  \\\"type\\\" : \\\"StillImage\\\",\\n  \\\"format\\\" : \\\"image/jpeg\\\",\\n  \\\"identifier\\\" : \\\"http://repo.rbge.org.uk/image_server.php?kind\\u003d1500\\u0026path_base64\\u003dL2hlcmJhcml1bV9zcGVjaW1lbl9zY2Fucy9FMDAvMzcwLzE4OC8xNzk2OTQuanBn\\\",\\n  \\\"references\\\" : null,\\n  \\\"title\\\" : null,\\n  \\\"description\\\" : \\\"Image of herbarium specimen E00370188 by Specimen Digitisation Pipeline\\\",\\n  \\\"source\\\" : null,\\n  \\\"audience\\\" : null,\\n  \\\"created\\\" : null,\\n  \\\"creator\\\" : \\\"Specimen Digitisation Pipeline\\\",\\n  \\\"contributor\\\" : null,\\n  \\\"publisher\\\" : null,\\n  \\\"license\\\" : \\\"http://creativecommons.org/publicdomain/zero/1.0/\\\",\\n  \\\"rightsHolder\\\" : \\\"Royal Botanic Garden Edinburgh\\\",\\n  \\\"datasetId\\\" : null\\n} ]\",\"Lens\",\"85\",\"bf2a4bf0-5f31-11de-b67e-b8a03c50a862\",\"2946873\",\"Vicia\",\"7707728\",\"Fabales\",\"TR\",\"Royal Botanic Garden Edinburgh\",\"Vicia lenticula (Hoppe) Janka\",\"Siehe, Walter\",\"1370\",\"E\",\"WrappedArray()\",\"Fabaceae\",\"ervoides\",\"574936220\",\"6\",\"herbarium specimen of unspecified type\",\"2974751\",\"PRESERVED_SPECIMEN\",\"0\",\"0\"],\"objatt_internal.created\":[\"0\"],\"sort_/publisher\":[\"Royal Botanic Garden Edinburgh\"],\"sort_/kingdom\":[\"Plantae\"],\"sort_/countryCode\":[\"TR\"],\"sort_/genericName\":[\"Lens\"],\"sort_/publishingorgkey\":[\"98e934b0-5f31-11de-b67e-b8a03c50a862\"],\"metadata/createdOn\":[\"0\"],\"dtindexed\":[\"20220126155304537\"],\"objatt_internal.modified\":[\"0\"],\"/order\":[\"Fabales\"],\"sort_/basisOfRecord\":[\"PRESERVED_SPECIMEN\"],\"/catalogNumber\":[\"E00370188\"],\"/gbifId\":[\"574936220\"],\"/datasetName\":[\"Royal Botanic Garden Edinburgh Herbarium (E)\"],\"sort_/recordedBy\":[\"Siehe, Walter\"]}\n");

    BulkEntryWriter writer =
        new BulkEntryWriter(settings, BulkCommands.create(settings, null, EsMajorVersion.V_7_X));
    BytesArray data = new BytesArray("{\"index\":{\"_id\":\"" + co.id + "\"}}\n" + result);

    writer.writeBulkEntry(data);

    BytesRef serialized = writer.writeBulkEntry(data);

    BulkProcessor processor = new BulkProcessor(client, writeResource, settings);
    processor.add(serialized);
    processor.flush();

    // System.out.println(client.postDocument(writeResource, document));

  }

  public static void main1(String[] args) throws Exception {
    DocumentBuilderElasticsearch builder = new DocumentBuilderElasticsearch(false, null);

    CordraObject occurrenceSchema = new CordraObject();
    occurrenceSchema.id = "an/unused/handle";
    CordraService.initializeSchemaObject(occurrenceSchema, "Occurrence", SCHEMA, null, 1, null);

    String baseUri =
        net.cnri.cordra.schema.SchemaUtil.getBaseUriFromSchemaCordraObject(occurrenceSchema);
    JsonNode node = JacksonUtil.gsonToJackson(occurrenceSchema.content);
    JsonNode schemaNode = JacksonUtil.getJsonAtPointer("/schema", node);

    LazySchema<JsonSchema> schemaO = new LazySchema(schemaNode, baseUri, occurrenceSchema);

    final SchemaNodeAndUri sn = new SchemaNodeAndUri(schemaO.getSchemaNode(), schemaO.getBaseUri());
    JsonSchemaFactory factory = JsonSchemaFactoryFactory.newJsonSchemaFactory(uri -> sn);

    JsonSchema schema = FgeJsonSchemaUtil.getJsonSchema(factory, schemaNode, baseUri);

    CordraObjectSchemaValidator validator =
        new CordraObjectSchemaValidator(null); // no cordra service

    CordraObject co = new CordraObject();
    co.id = "123";
    co.type = "Occurrence";
    // co.setContent("{\"scientificName\": \"Puma concolor\", \"bingo\": \"123\"}");
    // co.setContent("{\"scientificName\": \"Puma concolor\"}");

    Gson gson = new Gson();

    // Map<String, JsonNode> pointerToSchema =
    // validator.schemaValidateAndReturnKeywordsMap(JacksonUtil.gsonToJackson(co.content),
    // schemaNode, schema);
    Map<String, JsonNode> pointerToSchema = Maps.newHashMap();

    for (Map.Entry<String, JsonNode> e : pointerToSchema.entrySet()) {
      System.out.println(e.getKey() + " -> " + e.getValue().toString());
    }

    // ObjectMapper mapper = new ObjectMapper();
    // JsonNode typeSchema = mapper.readTree(SCHEMA);
    // Map<String, JsonNode> pointerToSchema = new HashMap<>();
    // pointerToSchema.put("Occurrence", typeSchema);
    Map<String, List<Object>> doc = builder.build(co, false, pointerToSchema, Lists.newArrayList());

    System.out.println(gson.toJson(doc));
  }
}
